/*
 * Copyright 2015 Mark Vedder
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package net.javaru.iip.frc.facet.ui;

import java.awt.*;
import javax.swing.*;

import org.jetbrains.annotations.Nls;
import org.jetbrains.annotations.NotNull;
import com.intellij.facet.ui.FacetEditorContext;
import com.intellij.facet.ui.FacetEditorTab;
import com.intellij.openapi.diagnostic.Logger;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import net.javaru.iip.frc.facet.FrcFacetConfiguration;



public class FrcFacetEditorTab extends FacetEditorTab
{
    private static final Logger LOG = Logger.getInstance(FrcFacetEditorTab.class);
    private final FacetEditorContext context;
    private final FrcFacetConfiguration frcFacetConfiguration;
    private JPanel rootPanel;


    public FrcFacetEditorTab(FacetEditorContext context, FrcFacetConfiguration frcFacetConfiguration)
    {
        this.context = context;
        this.frcFacetConfiguration = frcFacetConfiguration;
    }


    private void createUIComponents()
    {
        // TODO: place custom component creation code here 
    }


    @NotNull
    @Override
    public JComponent createComponent()
    {
        return rootPanel;
    }


    @Override
    public boolean isModified()
    {
        //TODO: Write this 'isModified' implemented method in the 'FrcFacetEditorTab' class
        LOG.debug("Yet to be implemented 'FrcFacetEditorTab.isModified()' method was called ");
        return false;
    }


    @Override
    public void reset()
    {
        //TODO: Write this 'reset' implemented method in the 'FrcFacetEditorTab' class
        LOG.debug("Yet to be implemented 'FrcFacetEditorTab.reset()' method was called ");
    }


    @Override
    public void disposeUIResources()
    {
        //TODO: Write this 'disposeUIResources' implemented method in the 'FrcFacetEditorTab' class
        LOG.debug("Yet to be implemented 'FrcFacetEditorTab.disposeUIResources()' method was called ");
    }


    @Nls
    @Override
    public String getDisplayName()
    {
        return "FRC Settings";
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JLabel label1 = new JLabel();
        label1.setText(" FRC facet");
        rootPanel.add(label1,
                      new GridConstraints(0,
                                          0,
                                          1,
                                          1,
                                          GridConstraints.ANCHOR_WEST,
                                          GridConstraints.FILL_NONE,
                                          GridConstraints.SIZEPOLICY_FIXED,
                                          GridConstraints.SIZEPOLICY_FIXED,
                                          null,
                                          null,
                                          null,
                                          1,
                                          false));
        final Spacer spacer1 = new Spacer();
        rootPanel.add(spacer1,
                      new GridConstraints(1,
                                          0,
                                          1,
                                          1,
                                          GridConstraints.ANCHOR_CENTER,
                                          GridConstraints.FILL_VERTICAL,
                                          1,
                                          GridConstraints.SIZEPOLICY_WANT_GROW,
                                          null,
                                          null,
                                          null,
                                          0,
                                          false));
    }


    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() { return rootPanel; }
}
