= FRC Wizard Templates
:toc:
:imagesdir: assets/images
:homepage: http://asciidoctor.org
:icons: font
:sectanchors:
:sectlinks:

== Freemarker Notes

=== Developer notes
* When committing Freemarker Template changes, do not allow IntelliJ IDEA to "Optimize Imports" (via said option in the commit dialog) as it will cause issues with the Freemarker templates with Java as the Template Data Language (reported via https://youtrack.jetbrains.com/issue/IDEA-226072[IDEA-226072])
* *Changes not picked up:* Sometimes after making a template change, upon testing, the change is not present. The template file does seem to change in both the `build` output and in the `.sandbox\plugins\FRC`. Nevertheless, the change does not (always) appear even after two restarts (i.e. two reruns of `clean build runIde`). Deleting IDEA's cache, by deleting the directory `.sandbox/system` seems to solve the issue. So it appears IDEA caches the resource and reuses the old version. More testing is needed to  confirm. And this may be resolved in newer versions of the `org.jetbrains.intellij` gradle plugin.

==== Location of "official" templates

* The gradle templates are in the https://github.com/wpilibsuite/vscode-wpilib[vscode-wpilib] project
** https://github.com/wpilibsuite/vscode-wpilib/tree/main/vscode-wpilib/resources/gradle/java[`build.gradle`] for Java projects
** https://github.com/wpilibsuite/vscode-wpilib/tree/main/vscode-wpilib/resources/gradle/javadt[`build.gradle`] for Java Desktop projects
** https://github.com/wpilibsuite/vscode-wpilib/tree/main/vscode-wpilib/resources/gradle/shared[shared files] such as `gradlew`, `settings.gradle`, etc. projects
* https://github.com/wpilibsuite/allwpilib/blob/master/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json[Example Details]
* https://github.com/wpilibsuite/allwpilib/blob/master/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/templates.json[Project Template Details]

==== Downloading Beta Versions of WPILib and VsCode

* Releases and Betas: https://github.com/wpilibsuite/allwpilib/releases
* Tags: https://github.com/wpilibsuite/allwpilib/tags



=== IntelliJ IDEA Project Template Data Language
In addition to error checking the Freemarker template, IntelliJ IDEA can error check the underlying language the template is looking to output. It calls this the "Template Data Language". By default, it will assume "HTML" as the "Template Data Language" -- that is it assume your template is outputting HTML -- and will apply HTML syntax highlighting and error checking to the template data (in addition to the Freemarker syntax highlighting and error checking to the overall file). This means that for a Java file template a line like this is highlighted as an error:
[source]
----
List<String> names = new ArrayList<>();
----
It will see the `<String>` as an "Unknown html tag 'String'". It will also have an error at the end of the document for an unclosed element. We can tell IntelliJ IDEA that our `*.java.ftl` files, such as  `Robot.java.ftl`, use Java as their Template Data Language, and thus all the data in it should be interpreted as producing Java and not HTML. (It is unfortunate that IntelliJ IDEA does not pick up the 'java' in the `.java.ftl` extension and automatically apply "Java" as the Template Data Language.)

We can do this on a per-file basis, a per-directory basis, as well as changing the default for the project from HTML to Java. Given that most of our templates are Java, it is generally easier to make the default for the project "Java" and then specify specific Data Template Languages for some directories and files. For example the "frc-wizard-templates/-DEFAULT-FILES-/gradle/groovy-dsl" directory can be set to "Groovy" and the "frc-wizard-templates/-DEFAULT-FILES-/gradle/kotlin-dsl" directory to "Kotlin". Note that you will need to do this for each year's templates.

You can make these settings in __**File | Settings | Languages & Frameworks | Template Data Languages**__ For an individual file, you can quickly get to this setting by putting your cursor on a highlighted error (such as `<String>` in the above example) and open the Quick Fix window via `Alt+Enter` and selecting the "__Change HTML template data language to…__" option. This will open the "Template Data Language" settings dialog with the path to the file prepopulated. Finally, even when the default Data Language is set to "<None>" in the "Template Data Language" settings, it seems like IntelliJ IDEA still uses HTML as the Data Language.

Because our Java templates place the package statement in an if block and uses a placeholder for the base package, IntelliJ IDEA will highlight an error (on the class name) saying "Missing package statement". We can suppress this for the file with a comment at the very top of the file just after the `<#ftl>` root tag. For example:

[source]
----
<#ftl output_format="plainText" encoding="UTF-8">
<#--noinspection WrongPackageStatement-->
----

== Updating/Creating Templates for new Season

In the below discussion, `20xx`, and in some cases `YYYY`, is used as a placeholder for the year being configured. For example, when configuring the 2022 templates, replace `20xx` (or `YYYY`) with `2022`.

There are multiple `wpilibsuite` projects we need to reference. The `vscode-wpilib` project contains the gradle and some other shared template files. However, the primary templates and examples are in the `allwpilib` project. There may be occasions that we need to reference the `allwpilib` the `GradleRIO` project.

.Default Files Directory
[NOTE]
The default files directory uses a name of `-DEFAULT-FILES-` so that is stands among the numerous directories, and so that it is sorted to the top of the list of directories. It contains both shared, and default file templates used by all the templates.

=== Part 1: Initial Copy

. In this project, update the `develop` branch and then create a `20xx-templates` branch from it.
. Clone and/or update the `main` branch of the `vscode-wpilib` project.
. Copy the previous year's templates `20xx` directory to the new year's name. You can use the copy refactoring.
    ** `src/main/resources/frc-wizard-templates/20xx`

=== Part 2 Update the Gradle templates and other files from the `vscode-wpilib` project

. Update the gradle version used in the templates:
    ** In the `vscode-wpilib` project, check the `vscode-wpilib/resources/gradle/shared/gradle/wrapper/gradle-wrapper.properties` file for its version, and update the `gradleDistributionUrl` `val` in `FrcProjectWizardData`
    ** Copy the two gradle wrapper scripts -- `gradlew` and `gradlew.bat` over from `vscode-wpilib/resources/gradle/shared` to `20xx/-DEFAULT-FILES-/gradle/gradle-wrapper/gradle`. This ensures true parity with the official templates, and scripts that will be in use world-wide.
. In the `vscode-wpilib` project, copy the entire contents of the `vscode-wpilib/resources/gradle/shared/settings.gradle` file to the clipboard. Then open our `src/main/resources/frc-wizard-templates/2023/-DEFAULT-FILES-/gradle/groovy-dsl/settings.gradle.ftl` file, and diff it to the clipboard. Make the necessary updates/changes. (The `frcYear` is set dynamically in our template wizard.) **Also update the `settings.gradle.kts.ftl` file.**
. In the `FrcWizardTemplateDefinitions.kt` file:
    ** Copy the previous year's `FrcWizard20xxProjectTemplateDefinition` and `FrcWizard20xxExampleTemplateDefinition` enum classes to ones named for the current year
    ** Update the `when` clause in `projectTemplateDefinitionsFor(Int)` function to add the current year, and "point" the else clause to the current year
    ** Update the `when` clause in `exampleTemplateDefinitionsFor(Int)` function to add the current year, and "point" the else clause to the current year
. The `build.gradle.ftl` and `build.gradle.kts.ftl` templates need to be updated. There is no one "easy" way to do this. The `vscode-wpilib` project uses several  files -- in the `java`, `javadt`, and `javaromi` directories -- whereas out project uses a single template file with `if` conditions and blocks. Ways to check and make updates:
    ** Look at the commit history for the various `build.gradle` files in the `vscode-wpilib` project.
    ** Diff sections of the various `build.gradle` files in the `vscode-wpilib` project to the corresponding `if` blocks in our template
    ** Generate a project via VS Code and the WPI plugin and our project wizard and compare/diff the results.
. Check the various `wpilib_preferences.json` files in the `vscode-wpilib` project and update our `frc-wizard-templates/20xx/-DEFAULT-FILES-/configs/.wpilib/wpilib_preferences.json.ftl` template file.
. Check the various `.vscode/settings.json` files in the `vscode-wpilib` project and update our `frc-wizard-templates/20xx/-DEFAULT-FILES-/extras/vs-code-configs/.vscode/settings.json.ftl` template file.

=== Part 3: Update common `-DEFAULT-FILES-` Freemarker templates and data

* In `FrcProjectWizardData`, update:
** `gradleDistributionUrl` if not done in Part 1
** `copyright` if needed
** `junit5Version` (until Enhancement #80 is implemented)
* Update the `WPILib-license.md` file
** Copy from `vscode-wpilib/resources/gradle/shared/WPILib-License.md`
** to `resources/frc-wizard-templates/20xx/-DEFAULT-FILES-/code/common-code/WPILib-License.md.ftl`


=== Part 4: Generate updated templates

. Clone and/or update the `main` branch in the `allwpilib` project.
*** You may need to turn on the action for the project in: File | Settings | Tools | Hungarian Notation Cleanup
. In the `allwpilib` project, in the `wpilibjExamples` module/subproject, for both the `templates` and `examples` directories in `wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates` directory, *do the following steps for each primary directory separately:*
.. Select the directory, and from the (right-click) context menu, run the "Hungarian Notation Cleanup" action from the HNC plugin.
.. After it initially runs -- which may take several minutes -- there will be a large "TODO" balloon pop-up explaining to do the following:
... In the "Find"Tool window, for each open tab, click the "Do Refactor" button.
... If presented with a popup about changed files, click the "Rerun search" button, and then click "Do Refactor" in the same tab again. The tab should then close. Sometimes you will need to run "Rerun search" 2 or 3 times for a tab.
... Repeat for each open tab. There may be numerous ones.
.. For the directory, from the context menu, run "Reformat Code", and then make sure to select "Include subdirectories" and "Optimize Imports" options.
.. **Complete the above for both the `templates` and `examples` directories before proceeding.**
. In `TemplatesPrepTool` (in this project at `src/main/java/net/javaru/iip/frc/templates/TemplatesPrepTool.kt`)
.. set `IS_DRY_RUN` to `true`
.. verify the `allwpilibProjectRootDir` path to the `allwpilib` project
.. Run a gradle clean
.. Run the `TemplatesPrepTool` in dry run mode
.. If there are any mapping issues reported, update the `dirMapping` Map **and the Template Definition enums** as appropriate.
... This finds any deleted and/or added templates
... You can also run a git history on the `templates` and `excamples` directories t confirm any addition and deletions
... When updating the enums, you can get the description from the `templates.json` and `examples.json` files.
... For any deleted/removed templates, also delete the corresponding directory
.. Once the mappings are resolved, set `IS_DRY_RUN` to `false`
.. Run `TemplatesPrepTool`
.. Check the output for any WARN messages and resolve as necessary.
. **Add the new templates to Git** (but do not commit yet)
. Run some checks on the templates be creating and building them. Some specific ones (due to their complexity and serving as good test cases) to check are:
** commandBased
** hatchBotInlined
** hatchBotTraditional
** romiReference
*** Do a Build & Run on this one to see if the simulation window opens correctly

== Part 5: One-off and Miscellaneous changes

* In `frc-wizard-templates/20xx/unitTesting/code/java-code/src/test/java/base-package/subsystems/IntakeTest.java.ftl`, add the comment `// To learn more about how to write unit tests, see the JUnit 5 User Guide at https://junit.org/junit5/docs/current/user-guide/` a line above the `@BeforeEach` method.

=== Part 6: Update Kotlin templates

Since there are no "official" Kotlin templates, we generally need to just see what has changed in the Java templates and apply them to the Kotlin templates. This can be done by doing a diff between the previous year's and the current year's Java templates, and/or by looking at the commit history on the templates in the `allwpilib` project.

== Update IntelliJ IDEA "Template Data Languages" settings
* File | Settings | Languages & Frameworks | Template Data Languages
* jetbrains://idea/settings?name=Languages+%26+Frameworks--Template+Data+Languages
* Can update in `.idea/templateLanguages.xml`
** Be sure to close project and then do the copy

.When doing commit
[IMPORTANT]
In the commit message, indicate the latest commit in the `allwpilib` project so that it is easy to track if there has been changes to templates since our last update. Also do a Git > History on the `wpilibjExamples/src/main/java/edu/wpi/first/wpilibj` directory and put that commit in the message as well.

.Example Commit Message
[source,text]
----
New Project Templates updates for 2022.
Current/latest commits in allwpilib project at time of update:
Project:
    109363da John Doe on 2021-12-09 at 15:29
    "Add remaining driver functions for REV (#3776)"
Templates `wpilibj` base dir:
    1ac02d2f Sara Moe on 2021-12-06 at 19:40
    "[examples] Fix drive Joystick axes in several examples (#3769)"
----