= FRC Wizard Templates
:toc:
:imagesdir: assets/images
:homepage: http://asciidoctor.org
:icons: font
:sectanchors:
:sectlinks:

== Freemarker Notes

=== Developer notes
* When committing Freemarker Template changes, do not allow IntelliJ IDEA to "Optimize Imports" (via said option in the commit dialog) as it will cause issues with the Freemarker templates with Java as the Template Data Language (reported via https://youtrack.jetbrains.com/issue/IDEA-226072[IDEA-226072])
* *Changes not picked up:* Sometimes after making a template change, upon testing, the change is not present. The template file did seem to change in both the `build` output and in the `.sandbox\plugins\FRC`, the change nevertheless appeared even after two restarts (i.e. two reruns of `clean build runIde`). Deleting IDEA's cache, by deleting the directory `.sandbox/system` seemed to solve the issue. So it appears IDEA was caching the resource and reusing the old version.

==== Location of "official" templates

* The gradle templates are in the https://github.com/wpilibsuite/vscode-wpilib[vscode-wpilib] project
** https://github.com/wpilibsuite/vscode-wpilib/tree/main/vscode-wpilib/resources/gradle/java[`build.gradle`] for Java projects
** https://github.com/wpilibsuite/vscode-wpilib/tree/main/vscode-wpilib/resources/gradle/javadt[`build.gradle`] for Java Desktop projects
** https://github.com/wpilibsuite/vscode-wpilib/tree/main/vscode-wpilib/resources/gradle/shared[shared files] such as `gradlew`, `settings.gradle`, etc projects
* https://github.com/wpilibsuite/allwpilib/blob/master/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/examples/examples.json[Example Details]
* https://github.com/wpilibsuite/allwpilib/blob/master/wpilibjExamples/src/main/java/edu/wpi/first/wpilibj/templates/templates.json[Project Template Details]

==== Downloading Beta Versions of WPILib and VsCode

* Releases and Betas: https://github.com/wpilibsuite/allwpilib/releases
* Tags: https://github.com/wpilibsuite/allwpilib/tags



=== IntelliJ IDEA Project Template Data Language
In addition to error checking the Freemarker template, IntelliJ IDEA can error check the underlying language the template is looking to output. It calls this the "Template Data Language". By default, it will assume "HTML" as the "Template Data Language" -- that is it assume your template is outputting HTML -- and will apply HTML syntax highlighting and error checking to the template data (in addition to the Freemarker syntax highlighting and error checking to the overall file). This means that for a Java file template a line like this is highlighted as an error:
[source]
----
List<String> names = new ArrayList<>();
----
It will see the `<String>` as an "Unknown html tag 'String'", It will also have an error at the end of the document for an unclosed element. We can tell IntelliJ IDEA that our `Robot.java.ftl` file is using Java as its Template Data Language and thus all the data in it should be interpreted as producing Java and not HTML. (It is unfortunate that IntelliJ IDEA does not pick up the 'java' in the `.java.ftl` extension and automatically apply "Java" as the Template Data Language.)

We can do this on a per file basis, a per directory basis, as well as changing the default for the project from HTML to Java. Given that most of our templates are Java, it is generally easier to make the default for the project "Java" and then specify specific Data Template Languages for some directories and files. For example the "frc-wizard-templates/-DEFAULT-FILES-/gradle/groovy-dsl" directory can be set to "Groovy" and the "frc-wizard-templates/-DEFAULT-FILES-/gradle/kotlin-dsl" directory to "Kotlin". Note that you will need to do this for each year's templates.

You can make these settings in __**File | Settings | Languages & Frameworks | Template Data Languages**__ For an individual file, you can quickly get to this setting by putting your cursor on a highlighted error (such as `<String>` in the above example) and open the Quick Fix window via `Alt+Enter` and selecting the "__Change HTML template data language to…__" option. This will open the "Template Data Language" settings dialog with the path to the file prepopulated. Finally, even when the default Data Language is set to "<None>" in the "Template Data Language" settings, it seems like IntelliJ IDEA still uses HTML as the Data Language.

Because our Java templates place the package statement in an if block and uses a placeholder for the base package, IntelliJ IDEA will highlight an error (on the class name) saying "Missing package statement". We can suppress this for the file with a comment at the very top of the file just after the `<#ftl>` root tag. For example:

[source]
----
<#ftl output_format="plainText" encoding="UTF-8">
<#--noinspection WrongPackageStatement-->
----

== Updating/Creating Templates for new Season

. Create (or copy over and update previous years) templates in `src/main/resources/frc-wizard-templates/YYYY`
** Be sure to check if gradle version used has been updated in the https://github.com/wpilibsuite/vscode-wpilib/tree/main/vscode-wpilib/resources/gradle/shared[gradle/shared] directory of the WPI `vscode-wpilib` project
. Create `FrcWizard####ProjectTemplateDefinition`, typically in `FrcWizardTemplateDefinitions.kt`
. Update `when` clause in `projectTemplateDefinitionsFor(Int)` function in `FrcWizardTemplateDefinitions.kt`
. Update `when` clause in `exampleTemplateDefinitionsFor(Int)` function in `FrcWizardTemplateDefinitions.kt`

=== Update common `-DEFAULT-FILES-` Freemarker templates and data

.Default Files Directory
[NOTE]
The default files directory uses a name of `-DEFAULT-FILES-` so that is stands among the numerous directories, and so that it is sorted to the top of the list of directories. It contains both shared, and default file templates used by all the templates.

* In `FrcProjectWizardData`, update:
** `gradleDistributionUrl`
*** look in `vscode-wpilib/resources/gradle/shared/gradle/wrapper/gradle-wrapper.properties`
*** Note it is in the `vscode-wpilib` and *not* `allwpilib` where the templates are
** `copyright` if needed
** `junit4Version` and `junit5Version` (until Enhancement #80 is implemented)
* `WPILib-license.md`
** `resources/frc-wizard-templates/2021/-DEFAULT-FILES-/code/common-code/WPILib-License.md.ftl`
** `vscode-wpilib/resources/gradle/shared/WPILib-License.md`
*** Note it is in the `vscode-wpilib` and *not* `allwpilib` where the templates are
* Gradle


=== Generating the templates:

. In the `allwpilib` project, in the `wpilibjExamples` module, on the `examples` and `templates` directories in `src/main/java/edu/wpi/first/wpilibj` directory, *for each primary template directory:*
.. Run the Hungarian Notation Cleanup action using the HNC plugin.
*** You may need to turn on the action for the project in File | Settings | Tools | Hungarian Notation Cleanup
.. Run "Reformat Code"
. In `TemplatesPrepTool`
.. set `IS_DRY_RUN` to `true`
.. verify the path to the `allwpilib` project
.. Run the in dry mode
.. If there are any mapping issues reported, update the `dirMapping` Map and the Examples Template Definition enum as appropriate
.. Once the mappings are resolved, set `IS_DRY_RUN` to `false`
.. Run
.. Check the output for any WARN messages
. Add the new templates to Git (but do not commit yet)
. Run some checks on the templates be creating and building them. Some specific ones (due to their complexity and serving as good test cases) to check are:
** commandBased
** hatchBotInlined
** hatchBotTraditional
** romiReference
*** Do a Build & Run on this one to see if the simulation window opens correctly

== Update IntelliJ IDEA "Template Data Languages" settings
* File | Settings | Languages & Frameworks | Template Data Languages
* jetbrains://idea/settings?name=Languages+%26+Frameworks--Template+Data+Languages
* Can update in `.idea/templateLanguages.xml`
** Be sure to close project and then do the copy

.When doing commit
[IMPORTANT]
In the commit message, indicate the latest commit in the `allwpilib` project so that it is easy to track if there has been changes to templates since our last update. Also do a Git > History on the `wpilibjExamples/src/main/java/edu/wpi/first/wpilibj` directory and put that commit in the message as well.

.Example Commit Message
[source,text]
----
New Project Templates updates for 2022.
Current/latest commits in allwpilib project at time of update:
Project:
    109363da John Doe on 2021-12-09 at 15:29
    "Add remaining driver functions for REV (#3776)"
Templates `wpilibj` base dir:
    1ac02d2f Sara Moe on 2021-12-06 at 19:40
    "[examples] Fix drive Joystick axes in several examples (#3769)"
----