# Based on "Gradle.gitlab-ci.yml" Template from https://gitlab.com/gitlab-org/gitlab-foss
#     https://gitlab.com/gitlab-org/gitlab-foss/-/blob/master/lib/gitlab/ci/templates/Gradle.gitlab-ci.yml

# Official Gradle Docker Images: https://hub.docker.com/_/gradle?tab=tags&page=1&ordering=last_updated
# as of gradle 7.3, "hotspot" JDK image (i.e. 7.4.2-jdk11-hotspot) is no longer available, but the "jdk11" version seems nearly identical
image: gradle:7.4.2-jdk11

# Disable the Gradle daemon for Continuous Integration servers as correctness
# is usually a priority over speed in CI environments. Using a fresh
# runtime for each build is more reliable since the runtime is completely
# isolated from any previous builds.
variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

build:
  stage: build
  script: gradle -Pis.ci.build=true --build-cache --stacktrace --info -x buildSearchableOptions clean buildPlugin
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: gradle -Pis.ci.build=true check
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
