/*
 * Copyright 2015-2017 Mark Vedder
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */
import java.nio.charset.StandardCharsets
import java.nio.file.*
import java.nio.file.attribute.BasicFileAttributes

buildscript {
  ext.kotlin_version = '1.1.50'

  repositories {
    mavenCentral()
    maven { url 'http://dl.bintray.com/jetbrains/intellij-plugin-service' }
    flatDir { dirs 'libs' }
  }
  dependencies {
    classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
  }
}

plugins {
  // https://github.com/JetBrains/gradle-intellij-plugin
  // also see http://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system/prerequisites.html
  id "org.jetbrains.intellij" version "0.2.17"
}

allprojects {
  //noinspection GroovyAssignabilityCheck
  tasks.withType(org.jetbrains.kotlin.gradle.tasks.KotlinCompile).all {
    kotlinOptions {
      // See https://kotlinlang.org/docs/reference/using-gradle.html#compiler-options
      jvmTarget = JavaVersion.VERSION_1_8.toString()
      javaParameters = true
      //noReflect = false
    }
  }
}

apply plugin: 'java'
apply plugin: 'kotlin'
apply plugin: 'org.jetbrains.intellij'
intellij {
  version ideaVersion
  pluginName 'FRC'
  downloadSources Boolean.valueOf(downloadIdeaSources)
  
  sameSinceUntilBuild Boolean.valueOf(isEAP)
  // alternativeIdePath = Absolute path to the locally installed JetBrains IDE. It makes sense to use this 
  // property if you want to test your plugin in WebStorm or any other non-IDEA JetBrains IDE. Empty value 
  // means that the IDE that was used for compiling will be used for running/debugging as well.  
  alternativeIdePath altIdeaPath
  updateSinceUntilBuild Boolean.valueOf(shouldUpdateSinceUntilBuild)
  
  plugins = []
  
  runIde {
    // example of setting system property keys for the IDE run
    runIde.systemProperties = ['key1': 'value1', 'key2': 'value2']
  }
  
  // See http://www.jetbrains.org/intellij/sdk/docs/tutorials/build_system/deployment.html
  publishPlugin {
    username 'javaru'
    password System.properties['intellij.publish.password']
    channels 'nightly'
  }
}

group 'com.example.groupId'
version = "${version}${buildNumber}"

sourceCompatibility = javaVersion
targetCompatibility = javaVersion
compileJava.options.encoding = 'UTF-8'
tasks.withType(JavaCompile) {
  options.encoding = 'UTF-8'
}

task wrapper(type: Wrapper) {
  // After modifying the version, run from cmd line: gradlew wrapper
  gradleVersion = '4.0'
}

repositories {
  mavenCentral()
  maven { url 'http://dl.bintray.com/jetbrains/intellij-plugin-service' }
  flatDir { dirs 'libs' }
}

Path sandboxConfigFile = Paths.get("${buildDir}/idea-sandbox/config/options/frc.xml")
Path configTmpFile
boolean preserveConfigFile = Boolean.parseBoolean(System.getProperty("frc.build.preserve.sandbox.config.file.on.clean", "true"))

clean.doFirst {
  if (preserveConfigFile && Files.exists(sandboxConfigFile))
  {
    configTmpFile = Files.createTempFile("frcConfig", ".xml")
    println(configTmpFile)
    Files.copy(sandboxConfigFile, configTmpFile, StandardCopyOption.REPLACE_EXISTING)
  }
}

clean.doLast {
  if (preserveConfigFile && configTmpFile != null && Files.exists(configTmpFile))
  {
    Files.createDirectories(sandboxConfigFile.getParent())
    Files.copy(configTmpFile, sandboxConfigFile, StandardCopyOption.REPLACE_EXISTING)
    try
    {
      configTmpFile.toFile().deleteOnExit()
      Files.deleteIfExists(configTmpFile)
    }
    catch (Exception ignore) {}
  }
  
}

prepareSandbox.doFirst {
  def logDir = "${buildDir}/idea-sandbox/system/log"
  def logDirPath = Paths.get(logDir)
  Files.createDirectories(logDirPath)
  Files.walkFileTree(logDirPath, new MyFileVisitor())
  def logFile = logDir + "/idea.log"
  def append = false
  def autoFlush = true
  def file = file(logFile)
  def writer = new PrintWriter(new OutputStreamWriter(new FileOutputStream(file, append), StandardCharsets.UTF_8), autoFlush)
  writer.flush()
  writer.close()
}


dependencies {
  compile group: 'org.jetbrains.kotlin', name: 'kotlin-stdlib-jre8', version: kotlin_version
  compile group: 'org.jetbrains.kotlin', name: 'kotlin-reflect', version: kotlin_version
  compile group: 'org.jetbrains.kotlin', name: 'kotlin-runtime', version: kotlin_version
  testCompile group: 'org.jetbrains.kotlin', name: 'kotlin-test', version: kotlin_version
  compile 'org.jdom:jdom2:2.0.6'
  compile 'commons-io:commons-io:2.5'
  compile 'org.apache.commons:commons-lang3:3.5'
  compile 'com.jcraft:jsch:0.1.54'
  testCompile group: 'junit', name: 'junit', version: '4.12'
}

class MyFileVisitor extends SimpleFileVisitor<java.nio.file.Path>
{
  boolean inThreadDumpsDir = false

  @Override
  FileVisitResult preVisitDirectory(java.nio.file.Path dir, BasicFileAttributes attrs) throws IOException
  {
    if (!inThreadDumpsDir)
    {
      inThreadDumpsDir = dir.getFileName().toString().startsWith("threadDumps-")
    }
    return FileVisitResult.CONTINUE
  }


  @Override
  FileVisitResult visitFile(java.nio.file.Path file, BasicFileAttributes attrs) throws IOException
  {
    if (inThreadDumpsDir)
    {
      Files.deleteIfExists(file)
    }
    return FileVisitResult.CONTINUE
  }


  @Override
  FileVisitResult postVisitDirectory(java.nio.file.Path dir, IOException exc) throws IOException
  {
    if (inThreadDumpsDir)
    {
      if (dir.getFileName().toString().startsWith("threadDumps-"))
      {
        // we're leaving the actual threadDumps dir (and not one of its sub directories) so we can reset the flag
        inThreadDumpsDir = false
      }
      Files.deleteIfExists(dir)
    }
    return FileVisitResult.CONTINUE
  }
}