#
# Copyright 2015-2021 the original author or authors.
#
#     Licensed under the Apache License, Version 2.0 (the "License");
#     you may not use this file except in compliance with the License.
#     You may obtain a copy of the License at
#
#       https://www.apache.org/licenses/LICENSE-2.0
#     
#     Unless required by applicable law or agreed to in writing, software
#     distributed under the License is distributed on an "AS IS" BASIS,
#     WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#     See the License for the specific language governing permissions and
#     limitations under the License.
#

# Properties can be overridden at runtime via a '-P' script parameter. For example:  -PideaVersion=IC-2017.1
#    In an IntelliJ IDEA Gradle Run/Debug Configuration, put it (including th4e -P) in the "Arguments" field (or "Script parameters" field fo older version of IntelliJ IDEA)

org.gradle.jvmargs=-Xms256m -Xmx1024m -Dfile.encoding=UTF-8
systemProp.file.encoding=utf-8
org.gradle.caching=true


frcPluginBaseVersion=1.5.1
# Leave blank for non EAPs, or set to "-eap.1", "-eap.2", etc.
frcPluginEapDesignator=

# VERSION EXAMPLES:
#    ideaVersion=IC-2021.2  
#    Pre first release, use either  LATEST-EAP-SNAPSHOT  or  212-EAP-SNAPSHOT  or a build number: IC-212.4746 
# Note 'LATEST-EAP-SNAPSHOT' does not work correctly with v1.1.4 of the ItelliJ Gradle Plugin. See https://github.com/JetBrains/gradle-intellij-plugin/issues/752
# ** Run a clean build (i.e. ./gradlew clean test buildPlugin) after updating/changing the ideaVersion or switching branches that changes the value **

ideaSinceBuild =212.4746
ideaUntilBuild =212.*
ideaMajorVersion=2021.2
ideaVersion=212-EAP-SNAPSHOT
verifierIdeVersions=IC-2021.2,IC-2021.2.3,IU-2021.2,IU-2021.2.3
#verifierLocalIdes=idea-IC-212.4746.2,idea-IC-212.4638.7
verifierLocalIdesBaseDir=~/.pluginVerifier/ides-local

# == V E R I F I E R == 
#  See: https://github.com/JetBrains/gradle-intellij-plugin#plugin-verifier-dsl
#       https://github.com/JetBrains/intellij-plugin-verifier#common-options
#  List of releases:
#       https://www.jetbrains.com/idea/download/other.html
#       All including EAPs RCs
#           https://data.services.jetbrains.com/products?fields=code,name,releases.downloads,releases.version,releases.build,releases.type&code=IIC,IIU,IIE
#       Just RCs & Releases:
#           https://data.services.jetbrains.com/products?fields=code,name,releases.downloads,releases.version,releases.build,releases.type&code=IIC,IIU,IIE&type=release,rc
#       Just Releases:
#           https://data.services.jetbrains.com/products?fields=code,name,releases.downloads,releases.version,releases.build,releases.type&code=IIC,IIU,IIE&type=release
#
# verifierLocalIdesBaseDir  ::  Absloute path to the base directory for locally installed IDEs. '~' is allowed to specify home directory.
#                               ex: verifierLocalIdesBaseDir=~/.pluginVerifier/ides-local
# verifierLocalIdes         ::  A Comma delimited list of subdirectory names containing extracted linux copy of IDE (located in the directory specified via verifierLocalIdesBaseDir)
#                               ex: verifierLocalIdes=idea-IC-212.4746.2,idea-IC-212.4638.7
# verifierIdeVersions       ::  A Comma delimited list of IDE versions to verfiy against
#                               ex:  verifierIdeVersions=IC-2020.1,IC-2020.1.3
