<?xml version="1.0" encoding="UTF-8"?>
<!--
  ~ Copyright 2015 Mark Vedder
  ~
  ~    Licensed under the Apache License, Version 2.0 (the "License");
  ~    you may not use this file except in compliance with the License.
  ~    You may obtain a copy of the License at
  ~
  ~      http://www.apache.org/licenses/LICENSE-2.0
  ~
  ~    Unless required by applicable law or agreed to in writing, software
  ~    distributed under the License is distributed on an "AS IS" BASIS,
  ~    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
  ~    See the License for the specific language governing permissions and
  ~    limitations under the License.
  -->

<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
    <modelVersion>4.0.0</modelVersion>


    <!--  Change assembly.xml file <includes> if you change the artifact coordinates -->
    <groupId>net.javaru.intellij-idea-plugins.intelliFRC</groupId>
    <artifactId>IntelliFRC-project</artifactId>
    <version>2015.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>IntelliFRC Project</name>

    <inceptionYear>2015</inceptionYear>

    <description>
        IntelliFRC is an IntelliJ IDEA plug-in for the US First (http://www.usfirst.org) First Robotics Competition (FRC).
        It is provided as an alternative to using the default Eclipse plug-in and programming environment.
        Best efforts will be made to keep it up to date. However it may lag a day or two behind the official Eclipse
        plug-in.
    </description>

    <organization>
        <name>Javaru</name>
    </organization>

    <licenses>
        <license>
            <name>The Apache Software License, Version 2.0</name>
            <url>http://www.apache.org/licenses/LICENSE-2.0.txt</url>
            <distribution>repo</distribution>
        </license>
    </licenses>

    <url>https://frc-intellij-idea.java.net</url>

    <scm>
        <url>https://hg.java.net/hg/frc-intellij-idea~scm</url>
        <connection>scm:hg:ssh://hg.java.net/frc-intellij-idea~scm</connection>
        <!--suppress MavenModelInspection -->
        <developerConnection>scm:hg:ssh://${java.net.username}@hg.java.net/intelliFRC~scm</developerConnection>
    </scm>

    <!--<ciManagement></ciManagement>-->

    <issueManagement>
        <system>Jira</system>
        <url>http://java.net/jira/browse/INTELLIFRC</url>
    </issueManagement>

    <modules>
        <module>frc-idea-plugin</module>
    </modules>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>1.8</java.version>

        <slf4j.version>1.7.2</slf4j.version>
        <logback.version>1.0.9</logback.version>

        <!--
            User must have the IDEA_HOME environment/shell variable set to the IntelliJ IDEA installation directory.
            For example: "C:/Program Files/JetBrains/IntelliJ IDEA 14.1"
        -->
        <!--<idea.home>${env.IDEA_HOME}</idea.home>-->
        <idea.home>P:\apps\IntelliJ IDEA\14.x</idea.home>
        <!-- Used to version the IntelliJ IDEA dependencies configured via systemPath declaration -->
        <idea.version>14.1</idea.version>
    </properties>

    <developers>
        <developer>
            <id>mvedder</id>
            <name>Mark Vedder</name>
            <!--<email>mark.vedder@frc.javaru.net</email>-->
            <url>http://java.net/people/272568-mvedder</url>
            <organization>Javaru.net</organization>
            <!--<organizationUrl>http://javaru.net</organizationUrl>-->
            <roles>
                <role>Lead</role>
                <role>Contributor</role>
                <role>Developer</role>
            </roles>
            <timezone>-5</timezone>
        </developer>
    </developers>


    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <artifactId>maven-assembly-plugin</artifactId>
                    <version>2.5.3</version>
                </plugin>
                <plugin>
                    <artifactId>maven-shade-plugin</artifactId>
                    <version>2.3</version>
                    <executions>
                        <execution>
                            <phase>package</phase>
                            <goals>
                                <goal>shade</goal>
                            </goals>
                            <configuration>
                                <transformers>
                                    <!-- Prevent "Unable to locate Spring NamespaceHandler for XML schema" errors -->
                                    <!-- See http://jira.codehaus.org/browse/MASSEMBLY-360?focusedCommentId=294888&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-294888-->
                                    <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                        <resource>META-INF/spring.handlers</resource>
                                    </transformer>
                                    <transformer implementation="org.apache.maven.plugins.shade.resource.AppendingTransformer">
                                        <resource>META-INF/spring.schemas</resource>
                                    </transformer>
                                    <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                        <mainClass>com.trgr.application.MyApp</mainClass>
                                    </transformer>
                                    <transformer implementation="org.apache.maven.plugins.shade.resource.ApacheNoticeResourceTransformer">
                                        <addHeader>false</addHeader>
                                    </transformer>
                                    <transformer implementation="org.apache.maven.plugins.shade.resource.ApacheLicenseResourceTransformer" />
                                    <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer" />
                                </transformers>
                                <filters>
                                    <!-- Prevent "Invalid signature file digest for Manifest main attributes" errors. See: http://stackoverflow.com/a/6743609/1348743 -->
                                    <filter>
                                        <artifact>*:*</artifact>
                                        <excludes>
                                            <exclude>META-INF/*.SF</exclude>
                                            <exclude>META-INF/*.DSA</exclude>
                                            <exclude>META-INF/*.RSA</exclude>
                                        </excludes>
                                    </filter>
                                </filters>
                            </configuration>
                        </execution>
                    </executions>
                </plugin>
                <plugin>
                    <artifactId>maven-project-info-reports-plugin</artifactId>
                    <version>2.8</version>
                    <configuration>
                        <!-- Enabling this may cause a significant slowdown -->
                        <dependencyLocationsEnabled>false</dependencyLocationsEnabled>
                    </configuration>
                </plugin>
            </plugins>
        </pluginManagement>

        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-compiler-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <source>${java.version}</source>
                    <target>${java.version}</target>
                </configuration>
            </plugin>
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <executions>
                    <execution>
                        <inherited>false</inherited>
                        <phase>package</phase>
                        <configuration>
                            <descriptors>
                                <descriptor>source-assembly.xml</descriptor>
                            </descriptors>
                            <outputDirectory>${project.basedir}</outputDirectory>
                            <attach>false</attach>
                        </configuration>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>







            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>2.4</version>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <copyright>Copyright 2015 Mark Vedder Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.</copyright>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-source-plugin</artifactId>
                <version>2.2.1</version>
                <executions>
                    <execution>
                        <id>attach-sources</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>jar-no-fork</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <copyright>Copyright 2015 Mark Vedder Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.</copyright>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-javadoc-plugin</artifactId>
                <!-- Also used in maven-site-plugin config - update version there as well -->
                <version>2.9</version>
                <executions>
                    <execution>
                        <id>attach-javadoc</id>
                        <phase>prepare-package</phase>
                        <goals>
                            <goal>jar</goal>
                        </goals>
                    </execution>
                </executions>
                <configuration>
                    <archive>
                        <manifestEntries>
                            <copyright>Copyright 2015 Mark Vedder Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with the License. You may obtain a copy of the License at http://www.apache.org/licenses/LICENSE-2.0 Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the specific language governing permissions and limitations under the License.</copyright>
                        </manifestEntries>
                    </archive>
                </configuration>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-enforcer-plugin</artifactId>
                <version>1.2</version>
                <executions>
                    <execution>
                        <id>enforce-versions</id>
                        <phase>compile</phase>
                        <goals>
                            <goal>enforce</goal>
                        </goals>
                        <configuration>
                            <rules>
                                <requireJavaVersion>
                                    <version>${java.version}</version>
                                </requireJavaVersion>
                            </rules>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-release-plugin</artifactId>
                <version>2.2.1</version>
                <dependencies>
                    <dependency>
                        <groupId>org.apache.maven.scm</groupId>
                        <artifactId>maven-scm-provider-hg</artifactId>
                        <version>1.5</version>
                    </dependency>
                </dependencies>
                <configuration>
                    <!-- All sub-modules use the same version -->
                    <autoVersionSubmodules>true</autoVersionSubmodules>
                    <goals>deploy</goals>
                </configuration>
            </plugin>
            <plugin>
                <!--
                    The changelog plugin uses version 1.3 of the SCM API and Hg provider by default.  There
                    is a bug in this version related to how the change set ids are extracted from the Mercurial
                    logs which breaks the ability to link to revisions in HgWeb.  The plugin definition
                    below isn't used per-se but the dependencies we have to override are carried through
                    to the report plugin.  See the section starting with 'Update' here:
                    http://www.sonatype.com/people/2008/04/how-to-override-a-plugins-dependency-in-maven/

                    The reporting plugin does not have the ability to override dependencies.  It is
                    an open feature request:  http://jira.codehaus.org/browse/MSITE-444
                -->
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-changelog-plugin</artifactId>
                <version>2.2</version>
                <dependencies>
                    <dependency>
                        <groupId>org.apache.maven.scm</groupId>
                        <artifactId>maven-scm-provider-hg</artifactId>
                        <version>1.5</version>
                    </dependency>
                    <dependency>
                        <groupId>org.apache.maven.scm</groupId>
                        <artifactId>maven-scm-api</artifactId>
                        <version>1.5</version>
                    </dependency>
                    <dependency>
                        <groupId>org.apache.maven.scm</groupId>
                        <artifactId>maven-scm-manager-plexus</artifactId>
                        <version>1.5</version>
                    </dependency>
                </dependencies>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.13</version>
                <configuration>
                    <workingDirectory>${basedir}/target</workingDirectory>
                    <forkMode>perthread</forkMode>
                    <perCoreThreadCount>true</perCoreThreadCount>
                    <!-- Count per CPU core-->
                    <threadCount>2</threadCount>
                    <argLine>-Dfile.encoding=UTF8</argLine>
                </configuration>
            </plugin>
            <plugin>
                <groupId>com.github.goldin</groupId>
                <artifactId>properties-maven-plugin</artifactId>
                <version>0.2.5</version>
                <executions>
                    <execution>
                        <id>set-properties</id>
                        <phase>pre-integration-test</phase>
                        <goals>
                            <goal>set-properties</goal>
                        </goals>
                        <configuration>
                            <properties>
                                <property>
                                    <name>isSnapshotBuild</name>
                                    <value>{{ project.version.contains('SNAPSHOT') }}</value>
                                </property>
                            </properties>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-gpg-plugin</artifactId>
                <version>1.4</version>
                <executions>
                    <execution>
                        <id>sign-artifacts</id>
                        <phase>verify</phase>
                        <goals>
                            <goal>sign</goal>
                        </goals>
                        <configuration>
                            <executable>C:\Program Files (x86)\GNU\GnuPG\2.x\gpg2.exe</executable>
                            <keyname>3C39F675</keyname>
                            <useAgent>true</useAgent>
                            <!--suppress MavenModelInspection -->
                            <skip>${isSnapshotBuild}</skip>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <artifactId>maven-site-plugin</artifactId>
                <version>3.2</version>
                <configuration>
                    <reportPlugins>
                        <plugin>
                            <artifactId>maven-project-info-reports-plugin</artifactId>
                        </plugin>
                        <!--<plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-checkstyle-plugin</artifactId>
                            <version>2.6</version>
                            <configuration>
                                <configLocation>checkstyle/supp_checks.xml</configLocation>
                            </configuration>
                        </plugin>-->
                        <plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-javadoc-plugin</artifactId>
                            <version>2.9</version>
                            <configuration>
                                <links>
                                    <link>http://docs.guava-libraries.googlecode.com/git-history/release/javadoc/</link>
                                    <link>http://docs.oracle.com/javase/${java.version}/docs/api/</link>
                                    <link>http://docs.oracle.com/javaee/5/api/</link>
                                </links>
                                <additionalJOption>-J-Dhttp.proxyHost=work.proxy.alais.url</additionalJOption>
                                <additionalJOption>-J-Dhttp.proxyPort=80</additionalJOption>
                                <additionalJOption>
                                    -J-Dhttp.nonProxyHosts="maven.a.wg|maven.r.wg|hudson.r.wg"
                                </additionalJOption>
                            </configuration>

                            <reportSets>
                                <reportSet>
                                    <id>default</id>
                                    <reports>
                                        <report>aggregate</report>
                                    </reports>
                                </reportSet>
                            </reportSets>
                        </plugin>
                        <plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-surefire-plugin</artifactId>
                        </plugin>
                        <plugin>
                            <groupId>org.codehaus.mojo</groupId>
                            <artifactId>taglist-maven-plugin</artifactId>
                            <version>2.4</version>
                        </plugin>
                        <plugin>
                            <groupId>org.apache.maven.plugins</groupId>
                            <artifactId>maven-changelog-plugin</artifactId>
                            <version>2.2</version>
                            <configuration>
                                <reports>
                                    <report>changelog</report>
                                    <report>dev-activity</report>
                                </reports>
                                <issueLinkUrl>http://java.net/jira/browse/SUPP</issueLinkUrl>
                                <!--suppress MavenModelInspection -->
                                <range>${changes.range}</range>
                                <dateFormat>EEE MMM d HH:mm:ss yyyy Z</dateFormat>
                            </configuration>
                        </plugin>
                    </reportPlugins>
                </configuration>
            </plugin>
        </plugins>
    </build>



    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.intellij.idea</groupId>
                <artifactId>annotations</artifactId>
                <version>${idea.version}</version>
                <systemPath>${idea.home}/lib/annotations.jar</systemPath>
                <scope>system</scope>
            </dependency>
            <dependency>
                <groupId>com.intellij.idea</groupId>
                <artifactId>extensions</artifactId>
                <version>${idea.version}</version>
                <systemPath>${idea.home}/lib/extensions.jar</systemPath>
                <scope>system</scope>
            </dependency>
            <dependency>
                <groupId>com.intellij.idea</groupId>
                <artifactId>resources</artifactId>
                <version>${idea.version}</version>
                <systemPath>${idea.home}/lib/resources.jar</systemPath>
                <scope>system</scope>
            </dependency>
            <dependency>
                <groupId>com.intellij.idea</groupId>
                <artifactId>resources_en</artifactId>
                <version>${idea.version}</version>
                <systemPath>${idea.home}/lib/resources_en.jar</systemPath>
                <scope>system</scope>
            </dependency>
            <dependency>
                <groupId>com.intellij.idea</groupId>
                <artifactId>idea</artifactId>
                <version>${idea.version}</version>
                <systemPath>${idea.home}/lib/idea.jar</systemPath>
                <scope>system</scope>
            </dependency>
            <dependency>
                <groupId>com.intellij.idea</groupId>
                <artifactId>openapi</artifactId>
                <version>${idea.version}</version>
                <systemPath>${idea.home}/lib/openapi.jar</systemPath>
                <scope>system</scope>
            </dependency>
            <dependency>
                <groupId>com.intellij.idea</groupId>
                <artifactId>forms_rt</artifactId>
                <version>${idea.version}</version>
                <systemPath>${idea.home}/lib/forms_rt.jar</systemPath>
                <scope>system</scope>
            </dependency>
            <dependency>
                <groupId>com.intellij.idea</groupId>
                <artifactId>icons</artifactId>
                <version>${idea.version}</version>
                <systemPath>${idea.home}/lib/icons.jar</systemPath>
                <scope>system</scope>
            </dependency>
            <dependency>
                <groupId>com.intellij.idea</groupId>
                <artifactId>util</artifactId>
                <version>${idea.version}</version>
                <systemPath>${idea.home}/lib/util.jar</systemPath>
                <scope>system</scope>
            </dependency>

            <dependency>
                <groupId>com.intellij.idea</groupId>
                <artifactId>groovy-plugin</artifactId>
                <version>${idea.version}</version>
                <systemPath>${idea.home}/plugins/Groovy/lib/Groovy.jar</systemPath>
                <scope>system</scope>
            </dependency>
            <dependency>
                <groupId>com.google.guava</groupId>
                <artifactId>guava</artifactId>
                <version>17.0</version>
                <systemPath>${idea.home}/lib/guava-17.0.jar</systemPath>
                <scope>system</scope>
            </dependency>
            <dependency>
                <groupId>org.apache.commons</groupId>
                <artifactId>commons-lang3</artifactId>
                <version>3.3.2</version>
            </dependency>
            <dependency>
                <groupId>uk.com.robust-it</groupId>
                <artifactId>cloning</artifactId>
                <version>1.9.1</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <dependencies>


    </dependencies>


</project>
