= FRC IntelliJ IDEA Plugin
v1.0, 2020-07-19
:imagesdir: assets/images
:homepage: https://gitlab.com/Javaru/frc-intellij-idea-plugin
:icons: font
:sectanchors:
:sectlinks:
:toc:
:toclevels: 3
:basedir: ../../../
:javasrcdir: {basedir}/src/main/java
ifdef::env-github[]
:caution-caption: :zap:
:important-caption: :exclamation:
:note-caption: :information_source:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

== About

An IntelliJ IDEA plugin for *https://www.firstinspires.org/[_FIRST_] Robotics Competition (https://www.firstinspires.org/robotics/frc[FRC])* robot development
in Java and Kotlin. This plugin works with either the free open-source Community Edition or Education Edition, or the licensed Ultimate Edition of IntelliJ IDEA.
More information available at the https://plugins.jetbrains.com/plugin/9405-frc[plugin's page] of the JetBrains Marketplace (formerly the JetBrains Plugin Repository.)


== Issues

Please report any issues or feature requests via the https://gitlab.com/Javaru/frc-intellij-idea-plugin/-/issues[Project's Issue Tracker].
Please note, that I use GitLab to host the project. You can https://gitlab.com/users/sign_in[log into] GiLab using your GitHub, Bitbucket, Twitter, or Google credentials if desired.
THis project is developed and maintained by an FRC Team mentor, hi 👋. Please do not contact _FIRST_ or the WPI Lib maintainers for support or issues. Submit an
issue at the above link and I will happily address it. Thanks.

=== Known Issues
==== Documentation needs updating

The documentation at this project's wiki is outdated. It has not been updated since the plugin was transition from Ant based projects to the Gradle based projects.
I will do my best to get it updated. But for the most part, the plugin's use is fairly intuitive.

[#eol-policy]
== End of Life Policy (i.e. IntelliJ IDEA versions supported)
Generally speaking, I will only maintain support for the latest two or three major releases of IntelliJ IDEA. (Please keep in mind that v2020.1 and v2020.2 are
both _major_ releases in the JetBrains versioning scheme.) I will do my best to support the latest three versions of IntelliJ IDEA if possible. But support may be limited
to the latest two major versions, or in very rare cases, only the latest/current major version.
When there are significant changes in the IntelliJ IDEA plugin APIs, or it becomes otherwise difficult to maintain support for older versions of IntelliJ IDEA,
I will discontinue support for those older versions, regardless of how many actively supported versions (beyond the current version) remain. This allows me to
implement new features using the newer plugin APIs, and migrate existing features off of deprecated parts of the plugin APIs. Sometimes these API changes are significant
and require a lot of refactoring work to bring the plugin up to date.

Trying to maintain support for numerous older versions would take _considerable_ time as the lines of development diverge, and would require me to implement/modify features
(and test them) multiple times, leveraging different APIs. I would much rather spend that time developing additional new features and additional improvements.
In other words, given the choice between say two new features for five or six versions of IntelliJ IDEA, or five or six new features for two or three versions of IntelliJ IDEA,
I would rather do the latter. And I believe most users would prefer that as well. Given that the FRC Plugin works fully with the free IntelliJ IDEA Community edition
(and Education edition), I do not think asking users to use a fairly current major version is overly burdensome. If you do not already use it, the
https://www.jetbrains.com/toolbox-app/[JetBrains Toolbox App] makes updating IntelliJ IDEA super easy, and it allows for multiple versions to easily coexist on your system.

The JetBrains release cycle adds some additional difficulties. The 20xx.3 version is typically released in late November to early December. This is of course just before build season
when I am busy implementing new WPILib features in the plugin. I do my best to support the new .3 version as soon as possible. But if incompatibilities exist, support may get delayed
while I focus on implementing new WPILib/FRC features required for the new build season. For example, the addition of the Command Based Robot v2 API for the 2020 season took considerable
time to implement support for, with that work taking place in December 2019 just as IntelliJ IDEA v2019.3 was released. Despite that, however, I was able to support v2019.3 for the
2020 competition season. That may not always be the case, however. Adding to the timing complexities, JetBrains typically releases v20xx.1 version in mid-March. Out Teams Regional
is always mid-March. As such, my duties as the Lead Software Developer, and typically software developer, for our team demand my full attention. This may delay my ability to provide support
to the 20xx.1 version upon its release.

=== Version Support Summary
In general, my goal *at Build Season Kick Off time* is:

* _Usually_ support the *.3 version* is released a couple of weeks prior to kick off
** For example, the December 2019 release of v2019.3 for the 2020 FRC season
** Any issues preventing immediate support will be fixed as soon as possible, but not at the cost of not supporting new primary WPILib/FRC features
** Historically, I have always been able to support the .3 version upon its release by JetBrains
* _Always_ support the *.2 version* released the year prior to kick off
** For example, v2019.2 for the 2020 FRC season
** The only exception _might_ be if the late implementation of a new WPILib/FRC feature would be best done using a plugin API introduced in the recent .3 version
* _If possible_, support the *.1 version* released in March during the build season and regional competitions
** For example, v2020.1 during the 2020 FRC season
** Since I am focused my mentoring duties, I may not be able to immediately implement an upgrade to support the new version, particularly if there are a large number of API changes
** It's recommended you check if a compatible version of the plugin is available prior to upgrading to the *.1 version* upon its release in March
* _If possible_, support the *.1 version* released the year prior to kick off
** For example, v2019.1 for the 2020 FRC season
** If the implementing of any new WPILib/FRC features require (or is best done) using new Plugin APIs introduced in the .2 version, .1 support will be ended.
** In general, it is more likely that the .1 version will *not* be supported
** .1 version support may end at any time during the build/competition season.
** .1 version will (almost) always end the summer after the build/competition season, if not ended previously.
* _Will most likely not support_ any previous releases. For example, none of the 2018.x versions (or prior) were supported for the 2020 build season.

=== Your best option
Below is the recommended timeframe for upgrades of IntelliJ IDEA

. *FRC pre-season* (i.e. September through December), use the latest .2 version.
** You should be fine using the .2 version through the build/competition season. But upgrading to the .3 version when supported is recommended.
. *Late December*, upgrade to the .3 version once the FRC plugin support for it is available (recommended).
. *During the build/competition season*, use .3 version if supported (it typically is) or the .2 version (being aware that while unlikely, support for it _may_ end mid-season)
** The subsequent .1 version is usually released in March or April. I do my best to support it when it is released. But continued use of the latest .3 version may be necessary.
. *Post competition season*, continue to either use the latest .3 version, or upgrade to the .1 version once supported.
. *August or September*, before the start of the school year / FRC pre-season, upgrade to the current .2 version to prepare for the next season.

[#plugin-versioning]
== Plugin Versioning
The plugin follows a versioning scheme of `[pluginVersion]-[ideaVersion]`. For example, version 1.3.0 of the plugin built for IntelliJ IDEA v2020.1 has a
version of `1.3.0-2020.1`, and version 1.3.0 of the plugin built for IntelliJ IDEA v2019.3 has a version of `1.3.0-2019.3`.

== Major Version
As of v2.x, the major version will increase for each FRC build season. Thus:

- version < = 1.x covered build seasons 2017-2021
- version 2.x was for build season 2022
- version 3,x for build season 2023
- version 4.x for build season 2024
- etc.

== Developing the Plugin

REMINDER: You must restart IntelliJ IDEA after setting or updating any environment variables.

The plugin uses some secrets and keys that can't be committed to source control. These values are loaded from a properties file. To allow for a token file to be 
shared across multiple project clones and to be optimally placed for security, the file's location is not predefined. Instead, it's location must be defined, as
a path, in the environment variable `FRC_PLUGIN_BUILD_REPLACEMENT_TOKENS_PROPERTIES_FILE`. This file must contain the keys:

  - `SENTRY_DSN_TEST_AND_QA`
  - `SENTRY_DSN_PROD`

If you wish to develop the plugin locally for your own use, you can bypass the need to define these keys, and thus the properties file, by setting the 
`frcPluginEapDesignator` property in the `gradle.properties` file to a value of `-UNOFFICIAL` (or alternatively `-SNAPSHOT`). 

== Code Signing

When building an official distribution, the following environment variables must be set, either on the syst4em.user level, or via the run/debug configuration
used to build the plugin for a release. The values provided are example values.

  - `JETBRAINS_MARKETPLACE_SIGNING_CERTIFICATE_CHAIN_FILE` -> C:\Users\USERNAME\AppData\Roaming\gnupg\Code-Signing-Keys\chain-2021-10-31--2022-10-30.crt
  - `JETBRAINS_MARKETPLACE_SIGNING_PRIVATE_KEY_FILE` -> C:\Users\USERNAME\AppData\Roaming\gnupg\Code-Signing-Keys\javaru-signing-private.pem
  - `JETBRAINS_MARKETPLACE_SIGNING_PRIVATE_KEY_PASSWORD`

See https://plugins.jetbrains.com/docs/intellij/plugin-signing.html[Plugin Signing] in the Jetbrains Plugins SDK documentation for more information.
