{
  "formatVersion": "1.1",
  "component": {
    "group": "com.asarkar",
    "module": "jsemver",
    "version": "0.6.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "fptu4j3hkbcobkevonrmi65324"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "jsemver-0.6.2.2.jar",
          "url": "jsemver-0.6.2.2.jar",
          "size": 70121,
          "sha512": "f030bfbbded04ac4c7c763af3bb4260ef1f958488dee404ac7a0c34ab700f941b8272ad0cde076810b243d6b4af317b644379e794b54f5019e5af8aaf0031cfb",
          "sha256": "3f37f7a80831740e1abbd22686f829383ae481e52c76541001c1855b08a1bf24",
          "sha1": "2209d015eb7e2af62a8e95a2ae43bab06aae1794",
          "md5": "b529859145cead76e980bd15b0204f15"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.localToProject": "public",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.antlr",
          "module": "antlr4-runtime",
          "version": {
            "requires": "4.8"
          }
        },
        {
          "group": "org.slf4j",
          "module": "slf4j-api",
          "version": {
            "requires": "1.7.30"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.4.10"
          }
        }
      ],
      "files": [
        {
          "name": "jsemver-0.6.2.2.jar",
          "url": "jsemver-0.6.2.2.jar",
          "size": 70121,
          "sha512": "f030bfbbded04ac4c7c763af3bb4260ef1f958488dee404ac7a0c34ab700f941b8272ad0cde076810b243d6b4af317b644379e794b54f5019e5af8aaf0031cfb",
          "sha256": "3f37f7a80831740e1abbd22686f829383ae481e52c76541001c1855b08a1bf24",
          "sha1": "2209d015eb7e2af62a8e95a2ae43bab06aae1794",
          "md5": "b529859145cead76e980bd15b0204f15"
        }
      ]
    }
  ]
}
