/*
 * Copyright 2015-2017 Mark Vedder
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package net.javaru.iip.frc.actions.create.ui.forms;

import java.awt.*;
import java.util.ResourceBundle;
import javax.swing.*;

import org.jetbrains.annotations.NotNull;
import com.intellij.openapi.diagnostic.Logger;
import com.intellij.ui.components.JBLabel;
import com.intellij.ui.components.JBTextField;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import net.javaru.iip.frc.actions.create.TaskValidator;
import net.javaru.iip.frc.actions.create.TaskValidatorBase;



public class CreateAntBuildPanelBean implements ModelPanelBean
{
    private static final Logger LOG = Logger.getInstance(CreateAntBuildPanelBean.class);


    private JPanel rootPanel;
    private JBTextField buildFileNameTextField;
    private JBTextField buildPropertiesNameTextField;


    public CreateAntBuildPanelBean()
    {
    }


    @NotNull
    @Override
    public JPanel getRootPanel() { return rootPanel; }


    @NotNull
    @Override
    public TaskValidator getTaskValidator()
    {
        return new TaskValidatorBase();
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(3, 3, new Insets(0, 0, 0, 0), -1, -1));
        final JBLabel jBLabel1 = new JBLabel();
        this.$$$loadLabelText$$$(jBLabel1, ResourceBundle.getBundle("messages/FrcBundle").getString("frc.new.class.command.action.dialog.build.file.label"));
        rootPanel.add(jBLabel1,
                      new GridConstraints(0,
                                          0,
                                          1,
                                          1,
                                          GridConstraints.ANCHOR_EAST,
                                          GridConstraints.FILL_NONE,
                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                          null,
                                          null,
                                          null,
                                          0,
                                          false));
        final Spacer spacer1 = new Spacer();
        rootPanel.add(spacer1,
                      new GridConstraints(0,
                                          2,
                                          1,
                                          1,
                                          GridConstraints.ANCHOR_CENTER,
                                          GridConstraints.FILL_HORIZONTAL,
                                          GridConstraints.SIZEPOLICY_WANT_GROW,
                                          1,
                                          null,
                                          null,
                                          null,
                                          0,
                                          false));
        final Spacer spacer2 = new Spacer();
        rootPanel.add(spacer2,
                      new GridConstraints(2,
                                          0,
                                          1,
                                          1,
                                          GridConstraints.ANCHOR_CENTER,
                                          GridConstraints.FILL_VERTICAL,
                                          1,
                                          GridConstraints.SIZEPOLICY_WANT_GROW,
                                          null,
                                          null,
                                          null,
                                          0,
                                          false));
        buildFileNameTextField = new JBTextField();
        buildFileNameTextField.setText("build.xml");
        rootPanel.add(buildFileNameTextField,
                      new GridConstraints(0,
                                          1,
                                          1,
                                          1,
                                          GridConstraints.ANCHOR_WEST,
                                          GridConstraints.FILL_NONE,
                                          GridConstraints.SIZEPOLICY_WANT_GROW,
                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                          null,
                                          new Dimension(150, -1),
                                          null,
                                          0,
                                          false));
        final JBLabel jBLabel2 = new JBLabel();
        this.$$$loadLabelText$$$(jBLabel2,
                                 ResourceBundle.getBundle("messages/FrcBundle").getString("frc.new.class.command.action.dialog.build.properties.label"));
        rootPanel.add(jBLabel2,
                      new GridConstraints(1,
                                          0,
                                          1,
                                          1,
                                          GridConstraints.ANCHOR_EAST,
                                          GridConstraints.FILL_NONE,
                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                          null,
                                          null,
                                          null,
                                          0,
                                          false));
        buildPropertiesNameTextField = new JBTextField();
        buildPropertiesNameTextField.setText("build.properties");
        rootPanel.add(buildPropertiesNameTextField,
                      new GridConstraints(1,
                                          1,
                                          1,
                                          1,
                                          GridConstraints.ANCHOR_WEST,
                                          GridConstraints.FILL_NONE,
                                          GridConstraints.SIZEPOLICY_WANT_GROW,
                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                          null,
                                          new Dimension(150, -1),
                                          null,
                                          0,
                                          false));
    }


    /** @noinspection ALL */
    private void $$$loadLabelText$$$(JLabel component, String text)
    {
        StringBuffer result = new StringBuffer();
        boolean haveMnemonic = false;
        char mnemonic = '\0';
        int mnemonicIndex = -1;
        for (int i = 0; i < text.length(); i++)
        {
            if (text.charAt(i) == '&')
            {
                i++;
                if (i == text.length()) break;
                if (!haveMnemonic && text.charAt(i) != '&')
                {
                    haveMnemonic = true;
                    mnemonic = text.charAt(i);
                    mnemonicIndex = result.length();
                }
            }
            result.append(text.charAt(i));
        }
        component.setText(result.toString());
        if (haveMnemonic)
        {
            component.setDisplayedMnemonic(mnemonic);
            component.setDisplayedMnemonicIndex(mnemonicIndex);
        }
    }


    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() { return rootPanel; }
}
