/*
 * Copyright 2015-2016 Mark Vedder
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package net.javaru.iip.frc.actions.create.ui.forms;

import java.awt.*;
import javax.swing.*;

import org.jetbrains.annotations.NotNull;
import com.intellij.ui.components.JBLabel;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;



public class DevWorkPanel implements PanelBean
{

    private JPanel myRootPanel;


    @NotNull
    @Override
    public JPanel getRootPanel() { return myRootPanel; }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        myRootPanel = new JPanel();
        myRootPanel.setLayout(new GridLayoutManager(3, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JBLabel jBLabel1 = new JBLabel();
        jBLabel1.setText("The quick brown fox");
        myRootPanel.add(jBLabel1,
                        new GridConstraints(0,
                                            0,
                                            1,
                                            1,
                                            GridConstraints.ANCHOR_CENTER,
                                            GridConstraints.FILL_NONE,
                                            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                            null,
                                            null,
                                            null,
                                            0,
                                            false));
        final Spacer spacer1 = new Spacer();
        myRootPanel.add(spacer1,
                        new GridConstraints(2,
                                            0,
                                            1,
                                            1,
                                            GridConstraints.ANCHOR_CENTER,
                                            GridConstraints.FILL_VERTICAL,
                                            1,
                                            GridConstraints.SIZEPOLICY_WANT_GROW,
                                            null,
                                            null,
                                            null,
                                            0,
                                            false));
        final JBLabel jBLabel2 = new JBLabel();
        jBLabel2.setText("jumped over the lazy dog.");
        myRootPanel.add(jBLabel2,
                        new GridConstraints(1,
                                            0,
                                            1,
                                            1,
                                            GridConstraints.ANCHOR_CENTER,
                                            GridConstraints.FILL_NONE,
                                            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                            GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                            null,
                                            null,
                                            null,
                                            0,
                                            false));
    }


    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() { return myRootPanel; }
}
