/*
 * Copyright 2015 Mark Vedder
 *
 *    Licensed under the Apache License, Version 2.0 (the "License");
 *    you may not use this file except in compliance with the License.
 *    You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 *    Unless required by applicable law or agreed to in writing, software
 *    distributed under the License is distributed on an "AS IS" BASIS,
 *    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *    See the License for the specific language governing permissions and
 *    limitations under the License.
 */

package net.javaru.iip.frc.ui;

import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Enumeration;
import javax.swing.*;

import com.intellij.openapi.diagnostic.Logger;
import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import net.javaru.iip.frc.settings.FrcSettings;



public class FrcSettingsForm
{
    private static final Logger LOG = Logger.getInstance(FrcSettingsForm.class);
    private FrcSettings frcSettings;
    private JPanel rootPanel;
    private JRadioButton targetWindowIsFrcToolWindowRadioButton;
    private JRadioButton targetWindowIsRunWindowRadioButton;
    private ButtonGroup rioLogTargetWindowButtonGroup;


    public FrcSettingsForm(FrcSettings frcSettings)
    {
        this.frcSettings = frcSettings;
        $$$setupUI$$$();
        postSetupComponentConfiguration();
        initForm();
    }


    private void initForm()
    {
        if (frcSettings.isRioLogTargetWindowIsFrcToolWindow())
        {
            rioLogTargetWindowButtonGroup.setSelected(targetWindowIsFrcToolWindowRadioButton.getModel(), true);
        }
        else
        {
            rioLogTargetWindowButtonGroup.setSelected(targetWindowIsRunWindowRadioButton.getModel(), true);
        }

        targetWindowIsRunWindowRadioButton.setActionCommand(RioLogTargetWindowActionCommands.RunWindow.name());
        targetWindowIsFrcToolWindowRadioButton.setActionCommand(RioLogTargetWindowActionCommands.FrcWindow.name());
    }


    private void createUIComponents()
    {
    }


    private void postSetupComponentConfiguration()
    {
        final Enumeration<AbstractButton> buttons = rioLogTargetWindowButtonGroup.getElements();
        while (buttons.hasMoreElements())
        {
            AbstractButton button = buttons.nextElement();
            button.addActionListener(new RioLogTargetWindowChangeActionListener());
        }

    }


    public JPanel getRootComponent()
    {
        return rootPanel;
    }


    public void importFrom(FrcSettings frcSettings)
    {
        this.frcSettings = frcSettings;
        initForm();
    }


    public boolean isSettingsModified(FrcSettings data)
    {
        return !this.frcSettings.equals(data);
    }


    public FrcSettings getFrcSettings()
    {
        return frcSettings;
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$()
    {
        rootPanel = new JPanel();
        rootPanel.setLayout(new GridLayoutManager(2, 1, new Insets(0, 0, 0, 0), -1, -1));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridLayoutManager(2, 2, new Insets(0, 0, 0, 0), -1, -1));
        rootPanel.add(panel1,
                      new GridConstraints(0,
                                          0,
                                          1,
                                          1,
                                          GridConstraints.ANCHOR_CENTER,
                                          GridConstraints.FILL_BOTH,
                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                          GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                          null,
                                          null,
                                          null,
                                          0,
                                          false));
        panel1.setBorder(BorderFactory.createTitledBorder("RIO Log Output Target Window"));
        targetWindowIsFrcToolWindowRadioButton = new JRadioButton();
        targetWindowIsFrcToolWindowRadioButton.setText("FRC Tool Window");
        targetWindowIsFrcToolWindowRadioButton.setToolTipText("RIO Log output qill appear in a dedicated FRC Tool Window");
        panel1.add(targetWindowIsFrcToolWindowRadioButton,
                   new GridConstraints(0,
                                       0,
                                       1,
                                       2,
                                       GridConstraints.ANCHOR_WEST,
                                       GridConstraints.FILL_NONE,
                                       GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                       GridConstraints.SIZEPOLICY_FIXED,
                                       null,
                                       null,
                                       null,
                                       1,
                                       false));
        targetWindowIsRunWindowRadioButton = new JRadioButton();
        targetWindowIsRunWindowRadioButton.setText("Run Window");
        targetWindowIsRunWindowRadioButton.setToolTipText("RIO LOg output will appear as a tab in the IDEA Run tool window.");
        panel1.add(targetWindowIsRunWindowRadioButton,
                   new GridConstraints(1,
                                       0,
                                       1,
                                       1,
                                       GridConstraints.ANCHOR_WEST,
                                       GridConstraints.FILL_NONE,
                                       GridConstraints.SIZEPOLICY_CAN_SHRINK | GridConstraints.SIZEPOLICY_CAN_GROW,
                                       GridConstraints.SIZEPOLICY_FIXED,
                                       null,
                                       null,
                                       null,
                                       1,
                                       false));
        final Spacer spacer1 = new Spacer();
        rootPanel.add(spacer1,
                      new GridConstraints(1,
                                          0,
                                          1,
                                          1,
                                          GridConstraints.ANCHOR_CENTER,
                                          GridConstraints.FILL_VERTICAL,
                                          1,
                                          GridConstraints.SIZEPOLICY_WANT_GROW,
                                          null,
                                          null,
                                          null,
                                          0,
                                          false));
        rioLogTargetWindowButtonGroup = new ButtonGroup();
        rioLogTargetWindowButtonGroup.add(targetWindowIsFrcToolWindowRadioButton);
        rioLogTargetWindowButtonGroup.add(targetWindowIsRunWindowRadioButton);
    }


    /** @noinspection ALL */
    public JComponent $$$getRootComponent$$$() { return rootPanel; }


    private class RioLogTargetWindowChangeActionListener implements ActionListener
    {
        @Override
        public void actionPerformed(ActionEvent e)
        {
            final ButtonModel selectedModel = rioLogTargetWindowButtonGroup.getSelection();
            final String actionCommandString = selectedModel.getActionCommand();
            LOG.info("Action Command = " + actionCommandString);
            final RioLogTargetWindowActionCommands actionCommand = RioLogTargetWindowActionCommands.valueOf(actionCommandString);
            switch (actionCommand)
            {
                case FrcWindow:
                    frcSettings.setRioLogTargetWindowIsFrcToolWindow(true);
                    break;
                case RunWindow:
                    frcSettings.setRioLogTargetWindowIsFrcToolWindow(false);
            }

        }
    }

    private static enum RioLogTargetWindowActionCommands
    {
        FrcWindow,
        RunWindow
    }

}
